// components/ui/mis/site-license-applicability/clra-threshold.ts

export const CLRA_THRESHOLD: Record<
  string,
  { state: number; central: number }
> = {
  "Andaman and Nicobar Islands": { state: 50, central: 20 },
  "Andhra Pradesh": { state: 50, central: 20 },
  "Arunachal Pradesh": { state: 50, central: 20 },
  Assam: { state: 50, central: 20 },
  Bihar: { state: 50, central: 20 },
  Chandigarh: { state: 20, central: 20 },
  CHATTISGARH: { state: 50, central: 20 },
  "Dadra and Nagar Haveli": { state: 20, central: 20 },
  "Daman and Diu": { state: 20, central: 20 },
  Delhi: { state: 20, central: 20 },
  Goa: { state: 50, central: 20 },
  Gujarat: { state: 50, central: 20 },
  Haryana: { state: 50, central: 20 },
  "Himachal Pradesh": { state: 30, central: 20 },
  "Jammu and Kashmir": { state: 20, central: 20 },
  Jharkhand: { state: 50, central: 20 },
  KARNATAKA: { state: 20, central: 20 },
  Kerala: { state: 20, central: 20 },
  Ladakh: { state: 20, central: 20 },
  Lakshadweep: { state: 20, central: 20 },
  "Madhya Pradesh": { state: 50, central: 20 },
  Maharashtra: { state: 50, central: 20 },
  Manipur: { state: 20, central: 20 },
  Meghalaya: { state: 20, central: 20 },
  Mizoram: { state: 20, central: 20 },
  Nagaland: { state: 20, central: 20 },
  ORISSA: { state: 50, central: 20 },
  PONDICHERRY: { state: 20, central: 20 },
  Punjab: { state: 50, central: 20 },
  Rajasthan: { state: 50, central: 20 },
  Sikkim: { state: 50, central: 20 },
  "Tamil Nadu": { state: 20, central: 20 },
  Telangana: { state: 10, central: 20 },
  Tripura: { state: 50, central: 20 },
  "Uttar Pradesh": { state: 50, central: 20 },
  Uttarakhand: { state: 20, central: 20 },
  "West Bengal": { state: 10, central: 20 },
}
